[server]
# Tillat at HTML/CSS/JS fungerer bedre i iframe
enableXsrfProtection = false
enableCORS = false
headless = true
runOnSave = true

[client]
# Forbedret støtte for kutt-og-lim i nettleser
browserGatherUsageStats = false

[theme]
# Følg systemets utseende
base = "light"
primaryColor = "#3498db"
backgroundColor = "#667eea"
secondaryBackgroundColor = "#f9f9f9"
textColor = "#2c3e50"

[global]
# Unngå advarsler om maks filstørrelse
deprecationWarning = false